plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mycompany.jarvis'
    compileSdk 34

    defaultConfig {
        applicationId "com.mycompany.jarvis"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
